# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ec414db50e3068b919e40e2349da65d609743bc72ee40f87d6f511016e713ef223248abc30696eaffc3fddf84325d0f11f0b34fb4987dc1564d668dd1a819e

test:
  secret_key_base: 74d2b1dc9d6dd797874cd85149caec53760051014ddcba52b252d4da917f5027a467bb4a7a3e9a64162fb1b103df40dceead9c51768f50f3679ec8a3fbcc6e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
